### ISSUE TITLE
I am intereseted in knowing how did you build this, the inner working.

### ISSUE THREAD

**Issue by aman5319** [dmlls/negate#4]
Hey man, first of all, this is an impressive project, I was hoping you can write a blog or article on how you used POS Tagging and Dependency Parser to build this.

I am interested in knowing this. if you can take some time out, please write an article on this.

**Comment by dmlls** [comment]
Hi @aman5319. Thanks for the kind words, really appreciate it!

I totally agree that writing an article would be helpful not only for those curious about the inner workings of negate, but also for those who want to contribute to the project.

Even though I haven't pushed any commits to the project in a while, I've been working on finetuning some models on negations and, if everything goes well, we will publish a paper about it by next month.

After that I should be able to dedicate more time again to negate (pun not intended). So I'll keep this one open just as a reminder, and I'll get back to you once the article is written 🙂

**Comment by dmlls** [comment]
@aman5319 Some update from my side: The paper has already been published. You can find it at https://anthology.aclweb.org/2023.inlg-main.12/. It includes some details of how negate works. Nevertheless, the article is still on my todo list!

**Comment by aman5319** [comment]
@dmlls, Thanks man, I will definitely read the paper on this weekend.

**Comment by aman5319** [comment]
I went through your paper and it's well written. I would love to work on it to bring multilingual support for Indian Languages.
