### ISSUE TITLE
Sentence failing

### ISSUE THREAD

**Issue by JohannesGetzner** [dmlls/negate#9]
**Describe the bug**
The following code:

```Python
from negate import Negator

negator = Negator()
negator.negate_sentence("A Python module to negate sentences.")
```
is erroneously returning:

```console
"A Python module to don't negate sentences."
```

<br>**Expected behavior**
The correct negated sentence should be:

```console
"A Python module to not negate sentences."
```

**Comment by dmlls** [comment]
@JohannesGetzner Great catch! Already fixed, will create a release now. Thanks!
